name: Build SBR Android App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20

      - name: Install Dependencies
        run: |
          npm install
          npm install @capacitor/android

      - name: Add and Sync Android Folder
        run: |
          npx cap add android || true
          npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Android AAB (Release)
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload Finished AAB
        uses: actions/upload-artifact@v4
        with:
          name: SBR-Release-App-Bundle
          path: android/app/build/outputs/bundle/release/*.aab

          
